[package]
name = "ruduino"
version = "0.1.1"
authors = [
  "The AVR-Rust Project Developers",
  "Jake Goulding <jake.goulding@gmail.com>",
]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/avr-rust/ruduino"
description = """
Reusable components for the Arduino Uno.
"""
keywords = ["avr", "arduino", "uno"]

[build-dependencies]
avr-mcu = "0.2"

